//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uStoreMVC.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public string TripName { get; set; }
        public string TripDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string TipImage { get; set; }
    }
}
